apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: test
spec:
  project: default

  source:
    repoURL: https://github.com/aqsa286/test_argcd.git
    targetRevision: HEAD
    path: kubernetes
  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
