apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace:
      name: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: .
    repoURL: 'https://github.com/aqsa286/test_argcd'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - Validate=false
